### PR TITLE
Fix unknown item filter

### PR DESCRIPTION
**Pull request by bdaylik**
Unknown item filter had a typo in CooccurenceAlgorithm. This PR tests and fixes the case.

### CODE REVIEW

**Comment by k4hoo** [comment]
Awesome! Thanks @bdaylik !
would you sign our contributor agreement? https://prediction.io/cla
Thanks

**Comment by bdaylik** [comment]
@k4hoo Just did!
Thanks

**Comment by k4hoo** [comment]
Thank! BTW, looks like the email you used for git commit is not linked to your github account

**Comment by bdaylik** [comment]
Thanks, that was my corporate mail. Its linked now :)

**Pull request merged**
