### PR TITLE
adding category blacklist

### LINKED ISSUE #7: Blacklist category
Is currently a way to blacklist certain categories?

### PR DESCRIPTION
**Pull request by alex9311**
resolve #7 

Did a simple test and it seems to work fine. 

Not sure what the desired behavior is for items without categories if both category blacklist and whitelist are used. In the original code items without categories were rejected if a category whitelist was used.

**Setup**

``` bash
$python data/import_eventserver.py --access_key $ACCESS_KEY

$pio build
$pio train
$pio deploy
```

**Check Regular Output**

``` bash
$ curl -H "Content-Type: application/json" -d '{ "items": ["i1"], "num": 2}' http://localhost:8000/queries.json
{"itemScores":[{"item":"i21","score":0.5954677866335736},{"item":"i43","score":0.5954677866335736}]}
```

**Check Categories on Returned Items**

``` bash
$curl -i -X GET "http://localhost:7070/events.json?accessKey=$ACCESS_KEY&entityId=i21"
[{"eventId":"ju3PNXbdlFIVrJvllSFn6AAAAVOzFictgvPavEwQRrg","event":"$set","entityType":"item","entityId":"i21","properties":{"categories":["c4"]},"eventTime":"2016-03-26T13:21:26.829Z","creationTime":"2016-03-26T13:21:26.831Z"}]

$curl -i -X GET "http://localhost:7070/events.json?accessKey=$ACCESS_KEYf&entityId=i43"
[{"eventId":"hofam3kIHfr4DiXaRggbZwAAAVOzFifPhpy0OKJE8d4","event":"$set","entityType":"item","entityId":"i43","properties":{"categories":["c2"]},"eventTime":"2016-03-26T13:21:26.991Z","creationTime":"2016-03-26T13:21:26.994Z"}]
```

**Blacklist Categories**

``` bash
$curl -H "Content-Type: application/json" -d '{ "items": ["i1"], "num": 2,"categoryBlackList":["c4"]}' http://localhost:8000/queries.json
{"itemScores":[{"item":"i43","score":0.5954677866335736},{"item":"i3","score":0.4273817248904073}]}

$curl -H "Content-Type: application/json" -d '{ "items": ["i1"], "num": 2,"categoryBlackList":["c2"]}' http://localhost:8000/queries.json
{"itemScores":[{"item":"i21","score":0.5954677866335736},{"item":"i3","score":0.4273817248904073}]}

$curl -H "Content-Type: application/json" -d '{ "items": ["i1"], "num": 2,"categoryBlackList":["c2","c4"]}' http://localhost:8000/queries.json
{"itemScores":[{"item":"i3","score":0.4273817248904073},{"item":"i8","score":0.40949795974796405}]}
```

### CODE REVIEW

**Comment by k4hoo** [comment]
Thanks @alex9311 ! Would you sign CLA https://prediction.io/cla/ so that I can merge your PR?

**Comment by alex9311** [comment]
Hey @k4hoo, just submitted it

**Comment by k4hoo** [comment]
@alex9311. Thanks for your contribution! would you like to update the SImilarProduct template doc for your changes too? https://github.com/PredictionIO/PredictionIO/tree/livedoc/docs/manual/source/templates/similarproduct

**Comment by alex9311** [comment]
yeah I'd be happy to, I'll submit a PR

**Comment by k4hoo** [comment]
Awesome! Thanks!

**Pull request merged**
